# Generated by Django 4.0.4 on 2022-05-09 09:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_yaml_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('data_inizio', models.DateField(default=None, null=True)),
                ('data_fine', models.DateField(default=None, null=True)),
                ('campi', django_yaml_field.fields.YAMLField()),
            ],
            options={
                'verbose_name_plural': 'Elementi',
            },
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('elementi', models.ManyToManyField(default=None, to='CurriculatorApp.elemento')),
            ],
            options={
                'verbose_name_plural': 'Sezioni',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascita', models.DateField(null=True)),
                ('luogo_nascita', models.CharField(blank=True, max_length=50, null=True)),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profili',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateField(default=datetime.date.today)),
                ('data_modifica', models.DateField(default=datetime.date.today)),
                ('profilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CurriculatorApp.profile')),
                ('sezione', models.ManyToManyField(default=None, to='CurriculatorApp.sezione')),
            ],
            options={
                'verbose_name_plural': 'Curriculum',
            },
        ),
    ]
