# Generated by Django 4.0.4 on 2022-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculatorApp', '0006_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='sezione',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='CurriculatorApp.sezione'),
        ),
        migrations.AlterField(
            model_name='sezione',
            name='elementi',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='CurriculatorApp.elemento'),
        ),
    ]
