# Generated by Django 4.0.4 on 2022-06-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculatorApp', '0009_alter_profile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='sezione',
            new_name='sezioni',
        ),
    ]
