# Generated by Django 4.0.4 on 2022-08-04 12:12

from django.db import migrations, models
import django.db.models.deletion
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculatorApp', '0010_rename_sezione_curriculum_sezioni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='sezioni',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='sezioni',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CurriculatorApp.sezione'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='campi',
            field=yamlfield.fields.YAMLField(),
        ),
        migrations.RemoveField(
            model_name='sezione',
            name='elementi',
        ),
        migrations.AddField(
            model_name='sezione',
            name='elementi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CurriculatorApp.elemento'),
        ),
    ]
