# Generated by Django 4.0.4 on 2022-08-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculatorApp', '0011_remove_curriculum_sezioni_curriculum_sezioni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='sezioni',
        ),
        migrations.RemoveField(
            model_name='sezione',
            name='elementi',
        ),
        migrations.AddField(
            model_name='elemento',
            name='sezione',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CurriculatorApp.sezione'),
        ),
        migrations.AddField(
            model_name='sezione',
            name='curriculum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CurriculatorApp.curriculum'),
        ),
    ]
