# Generated by Django 4.0.4 on 2022-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurriculatorApp', '0012_remove_curriculum_sezioni_remove_sezione_elementi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='data_fine',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='data_inizio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
